### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by hacknorris-code** [capJavert/clippy-dictionary#16]
idk what replies to add so im only making request here.

list of sites its lacking:

- mastodon.social && mastodon.online (cause federated, i think these enough)
- codeberg
- gitlab
- pixelfed.social
- tutanota mail
- proton mail/cloud, etc
- gdb compiler
- codeproject
- cyberchef (tool for hackers)
- also sites linked here cuz stux is my fren •w• : https://mstdn.social/about/more#services

and probly few more. just saying ;p

**Comment by capJavert** [comment]
Please follow https://github.com/capJavert/clippy-dictionary#contribute for contributions. Closing this but you are welcome to contribute to dictionary for any of these sites if you get some ideas.
